### ISSUE TITLE
TFCat validator

### ISSUE THREAD

**Issue by CorentinLouis** [CorentinLouis/SPACE_labelling_tool#9]
To validate the format of the TFCat catalogue, the `validate` function of `tfcat` package can be used

```
from tfcat.validate import validate_file
validate_file('my_catalogue_tfcat.json')
```

**Comment by smangham** [comment]
`tfcat` doesn't seem to be available through `pip install` - is this the version you use? https://gitlab.obspm.fr/maser/catalogues/tfcat

**Comment by CorentinLouis** [comment]
Yes it's indeed this version. 
I think you should be able to install it by doing:
`pip install git+https://gitlab.obspm.fr/maser/catalogues/tfcat.git`

(I just tested it, it seems to have worked well).

**Comment by smangham** [comment]
Unfortunately, that gives me a `Permission denied (publickey)` error, which it _shouldn't_ because I'm doing keyless SSH clone. Looking into it, it looks like the command fails when it attempts to pull in the JSON schema submodule... which is also public, do shouldn't require a key. Do you happen to have an SSH key registered on the GitLab?

**Comment by CorentinLouis** [comment]
This is indeed due to a submodule using the json Python package. It should have been removed for now, since it is not yet usefull.
Can you try again?

**Comment by smangham** [comment]
Installs fine on my office Mac - I'll leave this issue open until I've tested it on Ubuntu as well.

**Comment by smangham** [comment]
It no longer does! Fixed. I need to test it running to make sure I'm using it properly.
